myexplorer/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from .views import *
from django.contrib.auth.decorators import login_required

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'transfer.views.home', name='home'),
    # url(r'^transfer/', include('transfer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    # tab 1
    url(r'^manage_datamap/$', login_required(manage_datamap_view), name='manage_datamap'),
    url(r'^get_table_schema/$', login_required(get_table_schema_view), name='get_table_schema'),
    url(r'^table_schema/$', login_required(table_schema_view), name='table_schema'),
    url(r'^table_schema_no_adsnap/$', login_required(table_schema_no_adsnap_view), name='table_schema_no_adsnap'),
    url(r'^table_schema_transfer/$', login_required(table_schema_transfer_view), name='table_schema_transfer'),
        # ajax
        url(r'^table_column_hist/$', login_required(table_column_hist_view), name='table_column_hist'),
        url(r'^new_filter/$', login_required(new_filter_view), name='new_filter'),
        url(r'^add_to_filter/$', login_required(add_to_filter_view), name='add_to_filter'),
    # tab 2
    url(r'^manage_samples/$', login_required(manage_samples_view), name='manage_samples'),
    url(r'^upload_sample/$', login_required(upload_sample_view), name='upload_sample'),
    url(r'^filter_sample/$', login_required(filter_sample_view), name='filter_sample'),
    url(r'^sub_sample/$', login_required(sub_sample_view), name='sub_sample'),
    url(r'^merge_sample/$', login_required(merge_sample_view), name='merge_sample'),
    url(r'^review_samples/$', login_required(review_samples_view), name='review_samples'),
    url(r'^browse_sample/$', login_required(browse_sample_view), name='browse_sample'),
        url(r'^retrieve_sample_ajax/$', login_required(retrieve_sample_ajax_view), name='retrieve_sample_ajax'),
        url(r'^retrieve_osample_ajax/$', login_required(retrieve_osample_ajax_view), name='retrieve_osample_ajax'),
        url(r'^retrieve_oresult_ajax/$', login_required(retrieve_oresult_ajax_view), name='retrieve_oresult_ajax'),
        url(r'^sample_hist/$', login_required(sample_hist_view), name='sample_hist'),
    # tab 3
    url(r'^manage_analysis/$', login_required(manage_analysis_view), name='manage_analysis'),
    url(r'^canned_properties/$', login_required(canned_properties_view), name='canned_properties'),
    url(r'^canned_comparisons/$', login_required(canned_comparisons_view), name='canned_comparisons'),
        url(r'^calculate_properties_ajax/$', login_required(calculate_properties_ajax_view), name='calculate_properties_ajax'),
        url(r'^make_comparisons_ajax/$', login_required(make_comparisons_ajax_view), name='make_comparisons_ajax'),
    # tab 4
    url(r'^manage_reports/$', login_required(manage_reports_view), name='manage_reports'),
    url(r'^report/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.HTML_ROOT}, name='html_reports'),
    url(r'^database_reports/$', login_required(database_reports_view), name='database_reports'),
    url(r'^sample_reports/$', login_required(sample_reports_view), name='sample_reports'),
    url(r'^analysis_reports/$', login_required(analysis_reports_view), name='analysis_reports'),
    # default
    url(r'^download_mysql_db/', login_required(Download_Mysql_View), name='download_mysql'), # hack for now
    url(r'^', login_required(default_view), name='default'),
)

transfer/urls.py
from django.conf.urls import patterns, include, url
from myauth.views import *
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#urlpatterns = patterns('',
transfer_patterns = patterns('',
    # Examples:
    # url(r'^$', 'transfer.views.home', name='home'),
    # url(r'^transfer/', include('transfer.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


    #url(r'^explorer/',   include('explorer.urls', namespace='explorer')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout', mylogout_view, name='mylogout'),
    #url(r'^sampler/',   include('myexplorer.urls', namespace='myexplorer')),

    # direct domain
    url(r'^',   include('myexplorer.urls', namespace='myexplorer')),

    #url(r'^transfer/',   include('myexplorer.urls', namespace='myexplorer')),
    #url(r'^',               redirect_to, {'url': '/transfer/'})
    #url(r'^',               RedirectView.as_view(url='/transfer/'))
    #url(r'^', test_view, name='default'),
)

urlpatterns = patterns('',
    #url(r'^transfer/',          include(transfer_patterns)),
    url(r'^',               include(transfer_patterns)),
    #url(r'^',               RedirectView.as_view(url='/transfer/'))
)

myexplorer/forms.py
from django import forms
from .models import *
from django.forms.util import ErrorList

class Fixed_Ids_Upload_Form(forms.Form):
    sample_name = forms.CharField(
        label='Please name this sample', 
        max_length=50, 
        required=True, 
        error_messages={'required': 'You must name the sample'}
    )
    sample_key_column = forms.CharField(
        label='For reference enter sample key column', 
        max_length=50, 
        required=True, 
        error_messages={'required': 'example: EMPLID'}
    )
    csv_file = forms.FileField(label='Select a file', required=True, error_messages={'required': 'You must choose a file with ids one per line'})

class Sub_Sample_Form(forms.Form):
    sample = forms.ModelChoiceField(
        required=True, 
        label='Select a starting sample', 
        error_messages={'required': 'You must choose a sample'},
        queryset=Sample.objects.all().order_by('-id'), 
        widget=forms.Select(attrs={"onChange":"$('form').submit();"})
    )
    sub_size = forms.IntegerField(
        label='New sample size', 
        required=True, 
        widget=forms.TextInput(attrs={'placeholder':"size...", 'class':'input-large'})
    )
    sub_name = forms.CharField(
        max_length=50, 
        label='New sample name', 
        required=True, 
        widget=forms.TextInput(attrs={'placeholder':"name...", 'class':'input-large'})
    )
    def clean(self):
        if 'sample' in self.cleaned_data.keys() and 'sub_size' in self.cleaned_data.keys():
            olds = OSample.objects.filter(sample=self.cleaned_data['sample'])
            if self.cleaned_data['sub_size'] > len(olds):
                self._errors['sub_size'] = ErrorList(["Can not be bigger than starting sample size"])
        return self.cleaned_data
  
class Browse_Sample_Data_Form(forms.Form):
    sample = forms.ChoiceField(
        required=False
    )

    def __init__(self, choices, *args, **kwargs):
        super(Browse_Sample_Data_Form, self).__init__(*args, **kwargs)
        self.fields['sample'].choices = choices

class Retrieve_Schema_Form(forms.Form):
    trigger = forms.MultipleChoiceField(
        required=True, 
        widget=forms.CheckboxSelectMultiple,
        choices=(('trigger', "Yes, I'm sure, (takes about 10 minutes!)"),)
    )

class Filter_Select_Form(forms.Form):
    sfilter = forms.ModelChoiceField(
        required=True, 
        label='Select a Filter', 
        queryset=SampleFilter.objects.all().order_by('-id'), 
        widget=forms.Select(attrs={'onchange': "$('#theform').submit();"})
    )

class Sample_Filter_Cat_Form(forms.ModelForm):
    categories = forms.MultipleChoiceField(
        required=False, 
        widget=forms.SelectMultiple(attrs={'style': 'width:100%'}), 
        label=''
        )

    class Meta:
        model = SampleFilterPart
        fields = []

    def __init__(self, *args, **kwargs):
        super(Sample_Filter_Cat_Form, self).__init__(*args, **kwargs)
        self.fields['categories'].choices = self.instance.Cat_Choices()

    def label(self):
        mod = self.instance
        return ' . '.join([mod.ref, mod.table, mod.filter_col])

class Sample_Filter_Num_Form(forms.ModelForm):
    min_num = forms.CharField(
        max_length=50, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':"min: number", 'class':'input-large'}),
        error_messages={'invalid': 'Please enter a number'}
    )
    max_num = forms.CharField(
        max_length=50, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':"max: number", 'class':'input-large'}),
        error_messages={'invalid': 'Please enter a number'}
    )

    class Meta:
        model = SampleFilterPart
        fields = []

    def label(self):
        mod = self.instance
        return ' . '.join([mod.ref, mod.table, mod.filter_col])

    def clean_min_num(self):
        if self.cleaned_data['min_num'] == '':
            return ''
        try:
            return float(self.cleaned_data['min_num'])
        except:
            raise forms.ValidationError(self.fields['min_num'].error_messages['invalid'])
            return ''

    def clean_max_num(self):
        if self.cleaned_data['max_num'] == '':
            return ''
        try:
            return float(self.cleaned_data['max_num'])
        except:
            raise forms.ValidationError(self.fields['max_num'].error_messages['invalid'])
            return ''

class Sample_Filter_Date_Form(forms.ModelForm):
    min_date = forms.CharField(
        max_length=50, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':"min: yyyy-mm-dd", 'class':'input-large'}),
        error_messages={'invalid': "Please format: yyyy-mm-dd'"}
    )
    max_date = forms.CharField(
        max_length=50, 
        required=False, 
        widget=forms.TextInput(attrs={'placeholder':"max: yyyy-mm-dd", 'class':'input-large'}),
        error_messages={'invalid': "Please format: yyyy-mm-dd'"}
    )

    class Meta:
        model = SampleFilterPart
        fields = []

    def label(self):
        mod = self.instance
        return ' . '.join([mod.ref, mod.table, mod.filter_col])

    def clean_min_date(self):
        import datetime, time
        if self.cleaned_data['min_date'] == '':
            return ''
        try:
            data = self.cleaned_data['min_date']
            val = datetime.datetime.strptime(data, '%Y-%m-%d').date()
            tt = time.mktime(val.timetuple())
            return tt
        except:
            raise forms.ValidationError(self.fields['min_date'].error_messages['invalid'])
            return ''

    def clean_max_date(self):
        import datetime, time
        if self.cleaned_data['max_date'] == '':
            return ''
        try:
            data = self.cleaned_data['max_date']
            val = datetime.datetime.strptime(data, '%Y-%m-%d').date()
            tt = time.mktime(val.timetuple())
            return tt
        except:
            raise forms.ValidationError(self.fields['max_date'].error_messages['invalid'])
            return ''

class Table_Column_Data_Histogram_Form(forms.Form):
    hist_table_ref = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_table = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_column = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_type = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_numroundto = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput()) 
    hist_min_num = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_max_num = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_min_date = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_max_date = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_dateroundto = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput()) 
 
class Sample_Column_Data_Histogram_Form(forms.Form):
    hist_sample = forms.IntegerField(required=True, widget=forms.HiddenInput())
    hist_table_ref = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_table = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_column = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())
    hist_kind = forms.CharField(required=False, max_length=100, widget=forms.HiddenInput())

class New_Filter_Form(forms.Form):
    new_filter_name = forms.CharField(required=False, max_length=100)
    new_filter_join = forms.CharField(required=False, max_length=200, widget=forms.HiddenInput())

 
class Add_To_Filter_Form(forms.Form):
    addto_filter_name = forms.ModelChoiceField(
        required=False, 
        queryset=SampleFilter.objects.all().order_by('-id'), 
        label='Add to filter:'
    )
    addto_filter_table_ref = forms.CharField(max_length=100, widget=forms.HiddenInput())
    addto_filter_table = forms.CharField(max_length=100, widget=forms.HiddenInput())
    addto_filter_column = forms.CharField(max_length=100, widget=forms.HiddenInput())
    addto_filter_type = forms.CharField(max_length=100, widget=forms.HiddenInput())
 
class New_Sample_Form(forms.Form):
    new_sample_name = forms.CharField(
        max_length=50,
        required=False # javascript validation
    )
    new_sample_trigger = forms.BooleanField(
        required=False, 
        widget=forms.HiddenInput(),
        initial=False
    )
    test_sample_trigger = forms.BooleanField(
        required=False, 
        widget=forms.HiddenInput(),
        initial=False
    )
 
class Retrieve_Sample_Form(forms.Form):
    sample = forms.IntegerField(
        required=True, 
        widget=forms.HiddenInput(),
    )
 
class Retrieve_OSample_Form(forms.Form):
    osample = forms.IntegerField(
        required=True, 
        widget=forms.HiddenInput(),
    )

class Browse_Sample_Form(forms.Form):
    sample = forms.ModelChoiceField(
        required=True, 
        label='Select a sample', 
        error_messages={'required': 'You must choose a sample'},
        queryset=Sample.objects.filter(status='Loaded').order_by('-id'), 
        widget=forms.Select(attrs={"onChange":"$('#choose_sample_form').submit();"})
    )
    mod_osample = forms.IntegerField(
        required=True, 
        widget=forms.HiddenInput(),
        initial = 0
    )

class Properties_Sample_Form(forms.Form):
    sample = forms.ModelChoiceField(
        required=True, 
        label='Select a sample', 
        error_messages={'required': 'You must choose a sample'},
        queryset=Sample.objects.filter(status='Loaded').order_by('-id'), 
        widget=forms.Select(attrs={"onChange":"$('#properties_sample_form').submit();"})
    )

class Comparisons_Sample_Form(forms.Form):

myexplorer/templates/myexplorer/explore_tables.html
{% extends 'myexplorer/base_sampler.html' %}   

{% block title %}Database{% endblock %}

{% block head_extra2 %}

    <script type="text/javascript">

    $(document).ready(function() {
        // key bindings
        document.getElementsByTagName('body')[0].onkeyup = function(e) { 
            var ev = e || event;
            //alert (ev.keyCode);
            if(ev.keyCode == 78 && ev.ctrlKey) {
                alert('next')
            }
            if(ev.keyCode == 80 && ev.ctrlKey) {
                alert('prev')
            }
        }
        // right click context
        $('.context_table_column_data').contextMenu('menu_table_column_data', {
            bindings: {
                'text_summary': function(t) {
                    alert('text summary: '+t.id);
                },
                'graphical_summary': function(t) {
                    popup_histogram(t.id);
                },
                'new_filter': function(t) {
                    new_filter(t.id);
                },
                'add_to_filter': function(t) {
                    add_to_filter(t.id);
                }
            }
        });
    });
    // normal ajax
    function new_filter(data)
    {
        data = data.split(',');
        jQuery('#id_new_filter_join').val(data[0]+'.'+data[1]+'.'+data[2]);
        jQuery('#new_filter_message').html(data[0]+' . '+data[1]+' . '+data[2]);
        // popup modal dialog
        $('#new_filter_modal').modal('show');
    }
    function validate_new_filter()
    {
        fname = jQuery('#id_new_filter_name').val();
        if (fname.length < 1)
        {
            alert('you must name this filter');
            return 
        }
        var frm = $('#new_filter_form');
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(), // serializes the form's elements.
            success: function(data)
            {
                window.location.reload(true);
            }
         });
        return false; // avoid to execute the actual submit of the form.
    }
    function add_to_filter(data)
    {
        data = data.split(',');
        jQuery('#id_addto_filter_table_ref').val(data[0]);
        jQuery('#id_addto_filter_table').val(data[1]);
        jQuery('#id_addto_filter_column').val(data[2]);
        jQuery('#add_to_filter_message').html(data[0]+' . '+data[1]+' . '+data[2]);

        var dtype = data[3];
        if (dtype == 'NUMBER')
        {
            jQuery('#id_addto_filter_type').val('num');
        }
        else if (dtype == 'VARCHAR2')
        {
            jQuery('#id_addto_filter_type').val('cat');
        }
        else if (dtype == 'DATE')
        {
            jQuery('#id_addto_filter_type').val('date');
        }
        else
        {
            alert('unhandled datatype: '+dtype);
            return
        }
        // popup modal dialog
        $('#add_to_filter_modal').modal('show') 
    }
    function validate_add_to_filter()
    {
        fname = jQuery('#id_addto_filter_name').val();
        if (fname.length < 1)
        {
            alert('you must select a filter');
            return 
        }
        var frm = $('#add_to_filter_form');
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(), // serializes the form's elements.
            success: function(data)
            {
                alert(data);
                window.location.reload(true);
            }
         });
        return false; // avoid to execute the actual submit of the form.

    }
    // popup ajax
    function popup_histogram(data)
    {
        data = data.split(',');
        jQuery('#id_hist_table_ref').val(data[0]);
        jQuery('#id_hist_table').val(data[1]);
        jQuery('#id_hist_column').val(data[2]);
        var dtype = data[3];
        if (dtype == 'NUMBER')
        {
            jQuery('#id_hist_type').val('num');
            jQuery('#id_hist_numroundto').val(prompt_for_integer('please enter integer for rounding, or cancel to skip'));
            jQuery('#id_hist_min_num').val(prompt_for_number('please enter MIN value, or cancel to skip'));
            jQuery('#id_hist_max_num').val(prompt_for_number('please enter MAX value, or cancel to skip'));
        }
        else if (dtype == 'VARCHAR2')
        {
            jQuery('#id_hist_type').val('cat');
        }
        else if (dtype == 'DATE')
        {
            jQuery('#id_hist_type').val('date');
            jQuery('#id_hist_dateroundto').val(prompt_for_date_round("please enter 'day', 'week', 'month', or 'year' for date rounding"));
            jQuery('#id_hist_min_date').val(prompt_for_date("please enter MIN date 'yyyy-mm-dd'"));
            jQuery('#id_hist_max_date').val(prompt_for_date("please enter MAX date 'yyyy-mm-dd'"));
        }
        else
        {
            alert('unhandled datatype: '+dtype);
            return
        }
        if (confirm('Are you sure you want to create this histogram report?'))
        {
            var f = jQuery('#histogram_form');
            window.open('about:blank','histogram_window','toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=800,height=500,left = 312,top = 234');
            f.submit();
        }
        else 
            return
    }     
    function prompt_for_number(words)
    {
        var num = '';
        while(true)
        {
            ans = prompt(words);
            if(ans == null)
                break
            if(!isNaN(ans) && ans.length > 0)
            {
                num = ans;
                break
            }
        }
        return num
    }
    function prompt_for_integer(words)
    {
        var num = '';
        while(true)
        {
            ans = prompt(words);
            if(ans == null)
                break
            if(!isNaN(ans) && ans.length > 0 && parseInt(ans) == parseFloat(ans))
            {
                num = ans;
                break
            }
        }
        return num
    }
    function prompt_for_date_round(words)
    {
        var res = '';
        while(true)
        {
            ans = prompt(words);
            if(ans == null)
                break
            if(ans=='day' || ans=='week' || ans=='month' || ans=='year')
            {
                res = ans;
                break
            }
        }
        return res
    }
    function prompt_for_date(words)
    {
        start = new Date(1970,0,1)
        start = start.getTime()/1000;
        end = new Date()
        end = end.getTime()/1000;
        var mydate = '';
        var year = '';
        var month = '';
        var day = '';
        while(true)
        {
            ans = prompt(words);
            if(ans == null)
                break
            parts = ans.split('-');
            year = parts[0];
            month = parts[1];
            day = parts[2];
            // month has to be shifted
            if(!isNaN(month) && month.length > 0)
                month -= 1;
            try_secs = new Date(year, month, day)
            try_secs = try_secs.getTime()/1000;
            if( try_secs > start && try_secs < end) 
            {
                mydate = try_secs;
                break
            }
        }
        //alert(new Date(mydate*1000).toString());
        //alert(mydate);
        return mydate
    }
        
    </script>

{% endblock %}

{% block right_side %}

    <!-- Context Menus -->
    <div class="contextMenu" style="width:200px;" id="menu_table_column_data">
      <ul>
        <li id="text_summary">Text_Summary</li>
        <li id="graphical_summary">Histogram_Summary</li>
        <li id="new_filter">New_Sample_Filter</li>
        <li id="add_to_filter">Add_Filter_Option</li>
      </ul>
    </div>

    <!-- Modals -->
    <div id="new_filter_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">New Sample Filter</h3>
        </div>
        <div class="modal-body">
        Reference table column: <font color='blue'><span id='new_filter_message'></span></font>
        <br>
        <form id='new_filter_form' action="{% url 'myexplorer:new_filter' %}" method="post">{% csrf_token %}
        {{ new_filter_form.as_p }}
        </form>

        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary" onclick="validate_new_filter();">Save changes</button>
        </div>
    </div>

    <div id="add_to_filter_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Add Filter Option</h3>
        </div>
        <div class="modal-body">
        Ref.table.column: <font color='blue'><span id='add_to_filter_message'></span></font>
        <br>
        <form id='add_to_filter_form' action="{% url 'myexplorer:add_to_filter' %}" method="post">{% csrf_token %}
        {{ add_to_filter_form.as_p }}
        </form>

        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary" onclick="validate_add_to_filter();">Save changes</button>
        </div>
    </div>

    Number of Tables: {{tables|length}}
    {% for tt in tables%}
        <br>{{tt|safe}}
    {% endfor %}
    <hr>

    <form id='histogram_form' action="{% url 'myexplorer:table_column_hist' %}" method="post" target='histogram_window'>{% csrf_token %}
    {{ hist_form.as_p }}
    </form>

{% endblock %}

myexplorer/templates/myexplorer/filter_sample.html
{% extends 'myexplorer/base_sampler.html' %}   

{% block title %}Samples{% endblock %}

{% block head_extra2 %}

    <script type="text/javascript">
        function save_sample_dialog(e)
        {
            $('#new_sample_modal').modal('show');
        }
        function test_sample()
        {
            $('#id_test_sample_trigger').val(true);
            $('form').submit();
        }
        function save_sample_action()
        {
            var name = $('#id_new_sample_name').val();
            if(name.length > 0)
            {
                $('#id_new_sample_trigger').val(true);
                $('form').submit();
            }
            else
            {
                alert('Please enter a name for the sample');
                return
            }
        }
    </script>

{% endblock %}

{% block right_side %}
    <hr>
    Number of students: {{num_students}}
    <form id='theform' action="{% url 'myexplorer:filter_sample' %}" method="post">{% csrf_token %}
        <hr>
        {{filterform.sfilter.label}}<br>
        {{filterform.sfilter}}
        {% if sfilter.ref_table_column != None %}
            <br>
            Reference Table Column: <font color='blue'>{{sfilter.ref_table_column}}</font>
        {% endif %}
        {% comment %}
        {{filterformset.as_p}}
        {{filterformset.management_form}}
        {% endcomment %}
 
        <hr>
        <strong>Categoric Filter Options</strong>
        <br>
        {{catformset.management_form}}
        {% comment %}
        {{catformset.as_table}} 
        {% endcomment %}
        {% for form in catformset.forms %}
            <br>
            {{ form.id }}
            <font color='blue'>{{form.label}}</font>
            ( delete: {{ form.DELETE }} )
            <br>
            {{form.categories}}
        {% endfor %}
        <hr> 
        <strong>Numeric Filter Options</strong>
        <br>
        {{numformset.management_form}} 
        {% for form in numformset.forms %}
            <br>
            {{ form.id }}
            <font color='blue'>{{form.label}}</font>
            ( delete: {{ form.DELETE }} )
            <br>
            <font color='red'>{{form.min_num.errors}}</font>
            {{form.min_num}}
            <font color='red'>{{form.max_num.errors}}</font>
            {{form.max_num}}
        {% endfor %}
        <hr> 
        <strong>Date Filter Options</strong>
        <br>
        {{dateformset.management_form}} 
        {% for form in dateformset.forms %}
            <br>
            {{ form.id }}
            <font color='blue'>{{form.label}}</font>
            ( delete: {{ form.DELETE }} )
            <br>
            <font color='red'>{{form.min_date.errors}}</font>
            {{form.min_date}}
            <font color='red'>{{form.max_date.errors}}</font>
            {{form.max_date}}
        {% endfor %}
        {% comment %}
        {{formset.as_table}} 
        {% endcomment %}
        {% if sfilter.ref_table_column != None %}
            <br>
            <button class="btn" onclick="test_sample();">Test filter</button>
            <button class="btn" onclick="save_sample_dialog(); return false;">Save sample</button>
            <!-- Modals -->
            <div id="new_sample_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel">New Sample</h3>
                </div>
                <div class="modal-body">
                <br>
                {{ newsampleform.as_p }}
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <button class="btn btn-primary" onclick="save_sample_action(); return false;">Save changes</button>
                </div>
            </div>
        {% endif %}

    </form>

{% endblock %}

myexplorer/templates/myexplorer/get_students.html
{% extends 'myexplorer/base_sampler.html' %}   

{% block title %}Sampler - {% endblock %}

{% block head_extra %}
{% endblock %}

{% block right_side %}
    <hr>
    Existing Students: {{existing}}
    <br>
    Added Students: {{news|length}}
    {% for tt in news%}
        <br>{{tt}}
    {% endfor %}
    <hr>
{% endblock %}